export const GET_VEG_ITEMS = 'GET_VEG_ITEMS';
export const GET_NONVEG_ITEMS = 'GET_NONVEG_ITEMS';
export const GET_DESSERT_ITEMS = 'GET_DESSERT_ITEMS';


export const REMOVE_VEG_ITEMS = 'REMOVE_VEG_ITEMS';
export const REMOVE_NONVEG_ITEMS = 'REMOVE_NONVEG_ITEMS';
export const REMOVE_DESSERT_ITEMS = 'REMOVE_DESSERT_ITEMS';


export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';

export const REDUCE_QUANTITY = 'REDUCE_QUANTITY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';